sonar.projectKey=vishnukumar-vv_sonarqube
sonar.organization=vishnukumar-vv
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.binaries=.
