name: CI + Sonar + Artifactory

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Java setup
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Build
      - name: Build and Test
        run: mvn clean verify

      # 4. SonarCloud
      - name: SonarCloud Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=vishnukumar-vv_sonarqube \
            -Dsonar.organization=vishnukumar-vv \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # 5. Install JFrog CLI
      - name: Install JFrog CLI
        run: curl -fL https://install-cli.jfrog.io | sh

      # 6. Verify CLI
      - name: Verify CLI
        run: jf --version

      # 7. Configure Artifactory (FIXED)
      - name: Configure JFrog
        run: |
          jf config add artifactory-server \
          --url=${{ secrets.JFROG_URL }} \
          --access-token=${{ secrets.JFROG_PASSWORD }} \
          --interactive=false

      # 8. Test connection (VERY IMPORTANT)
      - name: Test Artifactory Connection
        run: jf rt ping

      # 9. Upload artifact
      - name: Upload Artifact
        run: jf rt u "target/*.jar" libs-release-local/

      # 10. Upload versioned artifact (best practice)
      - name: Upload Versioned Artifact
        run: |
          VERSION=$(date +%Y%m%d%H%M)
          jf rt u "target/*.jar" libs-release-local/myapp-$VERSION.jar
